// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geddraorjmehuimildnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZGRyYW9yam1laHVpbWlsZG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjk1ODMsImV4cCI6MjA3MTYwNTU4M30.IuzOqVuAVtagB5b_p0q55_g5grN75bL1_kgL3IvVfwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});